{% set ucx_version = "1.8.x" %}
{% set ucx_proc_version = "1.0.0" %}
{% set number = "0" %}

{% set ucx_proc_type = "gpu" %}


package:
  name: ucx
  version: {{ ucx_version }}

source:
  git_url: https://github.com/openucx/ucx.git
  git_ver: {{ ucx_version }}

build:
  skip: true  # [not linux]
  number: 0


requirements:
  build:
   - {{ compiler("c") }}
   - {{ compiler("cxx") }}
   - automake
   - autoconf
   - libtool
   - make
   - pkg-config
  host:

test:
  commands:
    - test -f "${PREFIX}/bin/ucx_info"
    # Requires driver for GPU test.
    - ${PREFIX}/bin/ucx_info -v
  
about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.

