# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge -c defaults .
{% set version = "0.14.0" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '10.2').split('.')[:2]) %}
package:
  name: libcugraph
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/cugraph
  git_ver: v{{ version }}
  patches:
    - cugraph_jetson.patch

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX

requirements:
  build:
    - cmake>=3.12.4
    - libcudf={{ minor_version }}
    - cudatoolkit {{ cuda_version }}.* # [ not aarch64 ]
    - boost-cpp>=1.66
    - libcypher-parser
    - nccl>=2.5
    - ucx-py {{ minor_version }}
  run:
    - libcudf={{ minor_version }}
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }} # [ not aarch64 ]
    - nccl>=2.5
    - ucx-py {{ minor_version }}

#test:
#  commands:
#    - test -f $PREFIX/include/cugraph.h


about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: libgraph library
