{% set version = "0.14.0" %}
{% set number = "1" %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '10.2').split('.')[:2]) %}

package:
  name: librmm
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/rmm.git
  git_rev: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
  run_exports:
    - {{ pin_subpackage("librmm", max_pin="x.x") }}

requirements:
  build:
    - cmake >=3.12.4
  host:
    - cudatoolkit {{ cuda_version }}.* # [ not aarch64 ]
    - spdlog >=1.4.2
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [ not aarch64 ]
    - spdlog >=1.4.2
    
test:
  commands:
    - test -f $PREFIX/include/rmm/rmm.h
    - test -f $PREFIX/include/rmm/rmm.hpp
    - test -f $PREFIX/include/rmm/rmm_api.h
    - test -f $PREFIX/include/rmm/thrust_rmm_allocator.h
    - test -f $PREFIX/include/rmm/detail/memory_manager.hpp
    - test -f $PREFIX/include/rmm/detail/cnmem.h
    - test -f $PREFIX/lib/librmm.so

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: librmm library
