# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = "0.14.0" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '10.2').split('.')[:2]) %}

package:
  name: libnvstrings
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/cudf.git
  git_rev: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - CUDA_VERSION
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
  run_exports:
    - {{ pin_subpackage("libnvstrings", max_pin="x.x") }}

requirements:
  build:
    - cmake >=3.12.4
  host:
    - librmm {{ minor_version }}.*
    - arrow-cpp 0.15.x
    - double-conversion
    - rapidjson
    - flatbuffers
    - boost-cpp
    - dlpack
  

test:
  commands:
    - test -f $PREFIX/include/nvstrings/NVCategory.h
    - test -f $PREFIX/include/nvstrings/NVStrings.h
    - test -f $PREFIX/include/nvstrings/NVText.h
    - test -f $PREFIX/include/nvstrings/StringsStatistics.h
    - test -f $PREFIX/include/nvstrings/base_category.h
    - test -f $PREFIX/include/nvstrings/ipc_transfer.h
    - test -f $PREFIX/include/nvstrings/numeric_category.h
    - test -f $PREFIX/lib/libNVCategory.so
    - test -f $PREFIX/lib/libNVStrings.so
    - test -f $PREFIX/lib/libNVText.so

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: libnvstrings library
