# Copyright (c) 2019, NVIDIA CORPORATION.

{% set version = "0.14.0" %}
{% set cuda_version = "10.2" %}
{% set py_version=environ.get('CONDA_PY', 35) %}

package:
  name: dask-cuda
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/dask-cuda.git
  git_rev: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - python x.x
    - setuptools
  run:
    - python x.x
    - dask-core >=2.4.0
    - distributed >=2.7.0
    - pynvml >=8.0.3
    - numpy >=1.16.0
    - numba >=0.40.1

test:
  imports:
    - dask_cuda

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: dask-cuda library
