# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = "0.14.0" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '10.2').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 35) %}

package:
  name: cudf
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/cudf.git
  git_rev: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PARALLEL_LEVEL
    - VERSION_SUFFIX

requirements:
  build:
    - python
    - cython 0.29.19
    - setuptools
    - numba >=0.49.0
    - dlpack
    - pyarrow 0.15.x
    - libcudf {{ version }}
    - rmm {{ minor_version }}.*
  run:
    - python
    - pandas >=0.25,<0.26
    - cupy >=6.6.0,<8.0.0a0,!=7.1.0
    - numba >=0.49.0
    - pyarrow 0.15.x
    - fastavro >=0.22.0
    - rmm {{ minor_version }}.*
    - nvstrings {{ minor_version }}.*
    - dlpack
    - fsspec>=0.6.0

test:
  commands:
    - python -c "import cudf"

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: cuDF GPU DataFrame core library
