# Copyright (c) 2020, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge -c defaults .
{% set version = "0.14.0" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA', '10.2').split('.')[:2]) %}
{% set cuda_major = environ.get('CUDA', '10.2').split('.')[0] %}
{% set cuda_minor = environ.get('CUDA', '10.2').split('.')[1] %}

package:
  name: libclx
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/clx
  git_ver: v{{ version }}

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX

requirements:
  build:
    - cmake>=3.14
    - libcudf={{ minor_version }}
    - cudatoolkit {{ cuda_version }}.* # [ not aarch64 ]
  run:
    - libcudf={{ minor_version }}
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [ not aarch64 ]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: libclx library
