# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = "0.14.0" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '10.2').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 35) %}

package:
  name: nvstrings
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/cudf.git
  git_rev: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - CUDA_VERSION
    - PARALLEL_LEVEL
    - VERSION_SUFFIX

requirements:
  build:
    - cmake >=3.12
  host:
    - python
    - setuptools
    - cmake_setuptools 0.1.3.*
    - libnvstrings {{ version }}
    - rmm {{ minor_version }}.*
  run:
    - python
    - rmm {{ minor_version }}.*

test:
  commands:
    - python -c "import nvstrings"
    - python -c "import nvtext"
    - python -c "import nvcategory"

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: nvstrings library
