# Copyright (c) 2018-2019, NVIDIA CORPORATION.

{% set version = "0.14.0" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: custreamz
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/cudf
  git_ver: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - python
  run:
    - python
    - streamz 
    - cudf {{ version }}
    - dask >=2.15.0
    - distributed >=2.15.0
    - python-confluent-kafka

test:
  imports:
    - cudf
    - streamz

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: cuStreamz library
