# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = "0.14.0" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 35) %}

package:
  name: ucx-py
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/ucx-py.git
  git_rev: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.14,<3.0.0a0
    - libhwloc
    - ucx
  run:
    - python
    - numpy
    - psutil
    - ucx
test:
  imports:
    - ucp

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  summary: libcudf library
