# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = "0.14.0" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '10.2').split('.')[:2]) %}
{% set cuda_major = environ.get('CUDA', '9.2').split('.')[0] %}
{% set cuda_minor = environ.get('CUDA', '9.2').split('.')[1] %}

package:
  name: libcuml
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/cuml.git
  git_rev: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - CUDA_VERSION
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
  run_exports:
    - {{ pin_subpackage("libcuml", max_pin="x.x") }}

requirements:
  build:
    - cmake >=3.14
    - clang=8.0.1
    - clang-tools=8.0.1
  host:
    - nccl >=2.5.*
    - cudf {{ minor_version }}
    - cudatoolkit {{ cuda_version }}.* # [ not aarch64 ]
    - ucx-py {{ minor_version }}
    - libcumlprims {{ minor_version }} # [ not aarch64 ]
    - liblapack
    - protobuf >=3.4.1,<4.0.0
  run:
    - libcumlprims=0.15.* # [ not aarch64 ]
    - cudf {{ minor_version }}
    - nccl>=2.5
    - ucx-py {{ minor_version }}
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }} # [ not aarch64 ]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  summary: libcudf library
