# Copyright (c) 2019, NVIDIA CORPORATION.

{% set version = "0.14.0" %}
{% set cuda_version = "10.2" %}
{% set py_version=environ.get('CONDA_PY', 35) %}

package:
  name: rmm
  version: {{ version }}

source:
  git_url: https://github.com/rapidsai/rmm.git
  git_rev: v{{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - RMM_BUILD_NO_GPU_TEST
    - VERSION_SUFFIX

requirements:
  build:
    - cmake >=3.12.4
  host:
    - python
    - librmm {{ version }}
    - setuptools
    - cython >=0.29,<0.30
  run:
    - python
    - numba >=0.49

test:
  commands:
    - python -c "import rmm"

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: rmm library
